apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  annotations:
    io.kubewarden.policy.category: Secure supply chain
    io.kubewarden.policy.severity: medium
  name: trusted-repos
spec:
  module: registry://ghcr.io/kubewarden/policies/trusted-repos:v2.0.6
#  mode: monitor
  settings:
    registries:
      allow:
        - registry.suse.com
        - registry.rancher.com
        - dp.apps.rancher.io
        - ghcr.io/kubewarden
        - ghcr.io/rancher
        - docker.io/rancher
#        - docker.io/alpine
        - docker.io/tiltdev # <- for the restart-helper extension, a simple go wrapper needed for instant update with interpreted languages
        - docker.io/library # <- local images built by Tilt (canonical name, nothing is published, it lives in local Rancher Desktop image store
    tags:
      reject:
        - bogus
  rules:
  - apiGroups:
    - ''
    apiVersions:
    - v1
    resources:
    - pods
    operations:
    - CREATE
    - UPDATE
  - apiGroups:
    - ''
    apiVersions:
    - v1
    resources:
    - replicationcontrollers
    operations:
    - CREATE
    - UPDATE
  - apiGroups:
    - apps
    apiVersions:
    - v1
    resources:
    - deployments
    - replicasets
    - statefulsets
    - daemonsets
    operations:
    - CREATE
    - UPDATE
  - apiGroups:
    - batch
    apiVersions:
    - v1
    resources:
    - jobs
    - cronjobs
    operations:
    - CREATE
    - UPDATE
  mutating: false
